### ISSUE TITLE
Is hausdorff projection necessary for basic energy evaluation?

### ISSUE THREAD

**Issue by pkerpedjiev** [ViennaRNA/forgi#17]
Is the Hausdorff projection necessary for basic sampling or should it only be required when trying to create 2D projections?

```
[pkerp@fluidspace ernwin] [master]$ ernwin_go.py --output-dir ~/papers/prospective/FRETtranslator/ernwin-data/ --log-to-file -i 50000 ~/data/cgs/3FU2.cg
/scr/fluidspace/pkerp/local/lib/python2.7/site-packages/forgi/threedee/utilities/average_stem_vres_atom_positions.py:2: UserWarning: Module average_stem_vres_atom_positions.py is depricated and buggy.
  warnings.warn("Module average_stem_vres_atom_positions.py is depricated and buggy.")
Traceback (most recent call last):
  File "/home/mescalin/pkerp/.virtualenvs/stuff/bin/ernwin_go.py", line 18, in <module>
    import fess.builder.energy as fbe
  File "/home/mescalin/pkerp/projects/ernwin/fess/builder/energy.py", line 29, in <module>
    import forgi.projection.hausdorff as fph
ImportError: No module named projection.hausdorff
```

**Comment by Bernhard10** [comment]
It is definitely not required for basic sampling. But it is part of newer forgi versions anyway, so there should be no harm done when importing it at the top level of the module.
Your traceback suggests that you use an older forgi version with a newer ernwin version.
